system.site:
  expected_config:
    mail: 'admin@example.com'
    name: 'Drush Site-Install'
    slogan: 'This is an example'
  update_actions:
    change:
      mail: wouter.adem@acquia.com
      name: 'Acquia Update Helper'
      slogan: 'This is an example'
